# Generated by Django 6.0.6 on 2026-06-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topgames',
            options={'ordering': ['position'], 'verbose_name': 'Top Games', 'verbose_name_plural': 'Top Games'},
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='main_developers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
