# Generated by Django 6.0.6 on 2026-06-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_topgames_options_game_description_game_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='main_developers',
        ),
    ]
