# Generated by Django 6.0.6 on 2026-06-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_main_developers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='games.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GameListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='games.gamelist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('game_list', 'position')},
            },
        ),
    ]
