# Generated by Django 6.0.6 on 2026-08-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_developer_game_developer'),
        ('games', '0004_gamelist_gamelistentry'),
    ]

    operations = [
    ]
