# Generated by Django 6.0.6 on 2026-08-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_merge_20260813_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='developer',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.developer'),
        ),
    ]
