# Generated by Django 6.0.6 on 2026-08-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_developer_developer_rawg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='rawg_id',
            new_name='igdb_id',
        ),
    ]
