# Generated by Django 6.0.6 on 2026-08-19 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_merge_20260819_1930"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower"],
                        name="games_follo_followe_212a48_idx",
                    ),
                    models.Index(
                        fields=["followed"],
                        name="games_follo_followe_54e278_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "followed"),
                        name="unique_follow",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("followed")),
                            _negated=True,
                        ),
                        name="no_self_follow",
                    ),
                ],
            },
        ),
    ]
